# PowerShell Script to Install Templates & Context
# Actions:
# 1. Create .github/ISSUE_TEMPLATE directories
# 2. Write ai_mission.yml (Strict AI Template)
# 3. Write human_task.yml (Standard Template)
# 4. Write CONTEXT.md (The Brain)

$repos = @("..\..\Production\website", "..\..\Production\lead-scraper")

$aiTemplate = @"
name: 🤖 AI Mission
description: Assign a task to the SporeSec AI Agent.
title: "[AI]: "
labels: ["agent:ai", "status:ready"]
assignees: ["SporeSec"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🤖 AI Mission Protocol
        **Target**: SporeSec Agent
        **Mode**: Deterministic
  - type: textarea
    id: objective
    attributes:
      label: Objective
      description: What is the specific goal?
      placeholder: Implement the User Login flow using IdentityServer.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Security & Brand Context
      description: Any specific constraints?
      value: "Refer to root CONTEXT.md for strict guidelines."
  - type: textarea
    id: success
    attributes:
      label: Success Criteria
      description: How do we know it's done?
    validations:
      required: true
"@

$humanTemplate = @"
name: 🧑‍💻 Human Task
description: Standard task for Co-Founders/Devs.
title: ""
labels: ["agent:human"]
assignees: []
body:
  - type: markdown
    attributes:
      value: "## Human Task"
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true
"@

$contextFile = @"
# SporeSec Development Context (The Brain)

> **CRITICAL**: Every AI Agent MUST read this file before modifying code.

## 1. Brand Identity
*   **Tone**: "Military-Grade", "Terminal-Chic", "Dark Web Intelligence".
*   **Colors**: Neon Green (#00FF00), Deep Black (#0a0a0a), Warning Red.
*   **Visuals**: Use 'Glassmorphism' and 'Monospace' fonts (Inter/JetBrains Mono).

## 2. Technology Stack (Immutable)
*   **Frontend**: Next.js 14+ (App Router), TailwindCSS v4, Framer Motion.
*   **Backend**: .NET 8, Clean Architecture.
*   **Scraper**: Golang, Colly, Rod (Headless).
*   **Database**: PostgreSQL / Redis (Queues).

## 3. Security Guidelines (Zero Trust)
*   **Never** commit secrets (check .gitignore).
*   **Always** validate inputs (Zod/FluentValidation).
*   **Tor**: All external requests MUST go through Tor Proxy.

## 4. Workflow
1.  Check Project Board "Agent Queue".
2.  Create Branch `feat/task-name`.
3.  Commit messages must be conventional (`feat: ...`, `fix: ...`).
4.  Open PR linked to Issue.

---
*Generated by SporeSec System*
"@

Write-Host "--- Installing System Files ---"

foreach ($repoPath in $repos) {
    Write-Host "Processing $repoPath..."
    
    # 1. Directories
    $issuePath = Join-Path $repoPath ".github\ISSUE_TEMPLATE"
    New-Item -ItemType Directory -Force -Path $issuePath | Out-Null
    
    # 2. Issue Templates
    Set-Content -Path (Join-Path $issuePath "ai_mission.yml") -Value $aiTemplate
    Set-Content -Path (Join-Path $issuePath "human_task.yml") -Value $humanTemplate
    
    # 3. Context (Root and .github/ for visibility)
    Set-Content -Path (Join-Path $repoPath "CONTEXT.md") -Value $contextFile
    
    # Also put in .github so it's hidden but accessible if preferred? 
    # User said "single file in every repo", root is best for Agents finding it.
    
    Write-Host "  -> Templates & Context Installed."
}

Write-Host "---------------------------------------------------"
Write-Host "Installation Complete."
Write-Host "---------------------------------------------------"
